language: c
os:
  - linux

compiler:
  - gcc
  - clang
  
install:
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov
  
addons:
  apt:
    packages:
      - cmake-data
      - cmake
      - libatlas-base-dev
      - python3
      - lcov
      - tree

script:
  - mkdir -p hmmmlib/build
  - cd hmmmlib/build
  - cmake .. 
  - make
  - ../build/exeHMMLIB
  - python3 --version
  - python3 ../../test_framework/test.py
  
after_success:
  - lcov --compat-libtool --directory . --capture --output-file coverage.info
  - coveralls-lcov coverage.info
  
branches:
  only:
    - master


