language: c
os:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
      - libatlas-base-dev
      - python3
      - lcov
      - tree

before_install:
  - pip install --user cpp-coveralls

script:
  - #CXXFLAGS="-g -O0 -Wall -W -Wshadow -Wunused-variable -Wunused-parameter -Wunused-function -Wunused -Wno-system-headers -Wno-deprecated -Woverloaded-virtual -Wwrite-strings -fprofile-arcs -ftest-coverage"
  - #CFLAGS="-g -O0 -Wall -W -fprofile-arcs -ftest-coverage"
  - #LDFLAGS="-fprofile-arcs -ftest-coverage"

  - mkdir -p hmmmlib/build
  - cd hmmmlib/build
  - cmake .. 
  - make
  - ../build/exeHMMLIB
  - python3 --version
  - python3 ../../test_framework/test.py
  - ./configure --enable-gcov && make && make check


after_success:
  # Create lcov report
  # capture coverage info
  - lcov --directory . --capture --output-file coverage.info
  # filter out system and extra files.
  # To also not include test code in coverage add them with full path to the patterns: '*/tests/*'
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  # output coverage data for debugging (optional)
  - lcov --list coverage.info
  - tree
  # Uploading to CodeCov
  # '-f' specifies file(s) to use and disables manual coverage gathering and file search which has already been done above
  #- bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

branches:
  only:
    - master


