language: c
os:
  - linux
  - osx
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
      - libatlas-base-dev

script:
  - mkdir -p hmmmlib/build; cd hmmmlib/build; cmake .. &&  make && ../build/exeHMMLIB


branches:
  only:
    - master

jobs:
  allow_failures:
    - os: osx