language: c
os:
  - linux

compiler:
  - gcc
  - clang
  
install:
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov
  
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
      - libatlas-base-dev
      - python3
      - lcov
      - tree

script:
  - mkdir -p hmmmlib/build
  - cd hmmmlib/build
  - cmake .. 
  - make
  - ../build/exeHMMLIB
  - python3 --version
  - python3 ../../test_framework/test.py


after_success:
  - make coverage
  - bash <(curl -s https://codecov.io/bash)
  
branches:
  only:
    - master


