language: c
os:
  - linux

compiler:
  - gcc
  - clang
  
addons:
  apt:
    packages:
      - cmake-data
      - cmake
      - libatlas-base-dev
      - python3
      - lcov
      - tree

script:
  - mkdir -p hmmmlib/build
  - cd hmmmlib/build
  - cmake .. 
  - make
  - ../build/exeHMMLIB
  - python3 --version
  - python3 ../../test_framework/test.py
  
branches:
  only:
    - master


